### ISSUE TITLE
What are the best configurations to run the "few-shot-vid2vid" model 

### ISSUE THREAD

**Issue by mamunctg** [NVlabs/few-shot-vid2vid#87]
Could anyone  please inform me the best configurations to train  the model ? I try to use the following configurations but it shows errors 
 for apex package. The apex packege can be solve if i use torch version = 1.6 but in the same time ,the flownet   shows errors.

I  used following configurations: python3.6, pytorch 1.2.0, torchvision 0.4.0, cuda 10.0, gcc4.9 in ubuntu-20.

##################ERROR######

(few_vid2vid) ***@ubuntu-***:$ python train.py --name face --dataset_mode fewshot_face --adaptive_spade --warp_ref --spade_combine --batchSize 8
/home/***/anaconda3/envs/few_vid2vid/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from models.models import create_model
  File "/home/****/few-shot-vid2vid/models/models.py", line 11, in <module>
    from models.networks.sync_batchnorm import DataParallelWithCallback
  File "/home/****/few-shot-vid2vid/models/networks/__init__.py", line 13, in <module>
    from models.networks.discriminator import *
  File "/home/****/few-shot-vid2vid/models/networks/discriminator.py", line 14, in <module>
    from models.networks.architecture import actvn as actvn
  File "/home/****/few-shot-vid2vid/models/networks/architecture.py", line 13, in <module>
    from models.networks.normalization import SPADE, SynchronizedBatchNorm2d
  File "/home/****/few-shot-vid2vid/models/networks/normalization.py", line 15, in <module>
    from apex.parallel import SyncBatchNorm as SynchronizedBatchNorm2d
  File "/home/****/anaconda3/envs/few_vid2vid/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/__init__.py", line 24, in <module>
    from . import transformer
  File "/home/***/anaconda3/envs/few_vid2vid/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/transformer/__init__.py", line 1, in <module>
    from apex.transformer import amp
  File "/home/****/anaconda3/envs/few_vid2vid/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/transformer/amp/__init__.py", line 1, in <module>
    from apex.transformer.amp.grad_scaler import GradScaler
  File "/home/****/anaconda3/envs/few_vid2vid/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/transformer/amp/grad_scaler.py", line 21, in <module>
    class GradScaler(torch.cuda.amp.GradScaler):
AttributeError: module 'torch.cuda' has no attribute 'amp'

**Comment by wangjinbo0929** [comment]
Did you fix this issue?I'm also getting the issue of AttributeError: module 'torch.cuda' has no attribute 'amp'

**Comment by wangjinbo0929** [comment]
Did you fix this issue?I'm also getting the issue of AttributeError: module 'torch.cuda' has no attribute 'amp' @mamunctg.Thank you
